services:
  accounts:
    image: "sahilkaul52/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sahilkaul
  loans:
    image: "sahilkaul52/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sahilkaul
  cards:
    image: "sahilkaul52/cards:v1"
    container_name: cards-ms
    ports:
      - "9003:9003"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sahilkaul
networks:
  sahilkaul:
    driver: "bridge"
