build:
  version: "2.0"


spring:
  config:
    activate:
      on-profile: "qa"


accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Rajesh - QA Lead"
    email: "rajesh123@gmail.com"
  onCallSupport:
    - (91) 555-1234-99
    - (22) 523-1345-77